### ISSUE TITLE
Google analytics support for Fire Fox

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/doc-it#328]
#### Describe the bug
Currently when viewing Doc'it via Fire Fox browser dev tools displays
- Some cookies are misusing the recommended “SameSite“ attribute.
- Cookie “_ga” has been rejected for invalid domain.
#### What is the expected behavior?
no cookie warnings for google analytics

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io using Fire Fox browser
2. Open dev tools and refresh
3. Warnings displayed

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/103570932-ff964b00-4e97-11eb-87ff-64088f05286d.png)

#### Anything else to add?
https://stackoverflow.com/questions/62569419/how-to-set-secure-attribute-of-the-cookies-used-by-google-analytics-global-sit

**Comment by huayunh** [comment]
**ahem**

**Comment by huayunh** [comment]
This appears to have been fixed in the upperstream. Closing the issue.
