### ISSUE TITLE
Unrecognized feature: 'interest-cohort'

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#407]
## Describe the bug

When I go to docit (dev or master), I see this console warning: 

```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
```

## What is the expected behavior?

No warning?

## Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/118509845-6d803800-b6fe-11eb-8124-c7f4d7730f3e.png)

## Environment
MacOS Chrome. **This seems to be a chrome-specific issue,** as I tried on Firefox and Safari and none have this problem.

**Comment by jeffvg** [comment]
https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/

**Comment by huayunh** [comment]
Check if there is a new React GA, maybe it would update

**Comment by huayunh** [comment]
Can verify that this has dissolved by itself.
