### ISSUE TITLE
bugLabels didn't get used

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#443]
#### Describe the bug

In developer resources page, the `bugLabels` prop didn't get properly passed in to `ButtonRow`

#### What is the expected behavior?

Link should take users to the proper bug page

**Comment by daileytj** [comment]
For repos that have more than one package in them, make sure that the bug link links to the issues tab with those labels only. (Will potentially need to add more labels)

**Comment by huayunh** [comment]
can verify this has been fixed by BLUIfiation.
