### ISSUE TITLE
In dev mode, auto refresh cause IconDrawer accessed before initialization

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#456]
#### Describe the bug
```
ReferenceError: Cannot access 'IconDrawer' before initialization
```

#### What is the expected behavior?

Auto-refresh shall work

#### What are the steps to reproduce?
1. `yarn start`
2. go to the icon-library (formerly iconography) /style/icon-library page, observe that everything gets rendered properly
3. randomly change something
4. waiting for the server to auto-refresh
5. observe RSOD
6. refresh using browser refresh
7. everything back to normal

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/129994113-61f6c687-b62b-41ea-8863-1eb0ec3c7efb.png)

#### Environment

Mac Big Sur Chrome
		
#### Anything else to add?

This is only in dev. Everything in build works fine.

I can live with refreshing... just annoying.

**Comment by huayunh** [comment]
Leave this open

**Comment by bkarambe** [comment]
@huayunh I am not able to reproduce this issue. Can you please confirm, whether it is already been fixed?

**Comment by huayunh** [comment]
The issue still exists in dev, but it looks like it has been miraculously fixed in the MUIv5 branch.
