### ISSUE TITLE
Iconography page giving wrong instructions for icon fonts when there are consecutive numbers

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#486]
### Describe the bug

For icons named `ev_plug_iec_60309_2_xxx` (there are four of them), docit is omitting the dash in `_2` part of the name, and the icon name is listed to be `ev_plug_iec_603092_xxx`

### What is the expected behavior?

It should name correctly. This applies to icon fonts and SVG instructions.

### What are the steps to reproduce?
1. docit needs to upgrade to icons-mui v2.8.0^ first
2. Checkout an icon named as described (for example, /style/iconography?icon=EvPlugIec603092Three32&isMaterial=false)
3. Check the instructions in the side panel

### Screenshots or links to minimum reproduction example
Highlighted instructions should be identical
![image](https://user-images.githubusercontent.com/8997218/145590911-1a3c9a40-f0ef-4156-a32c-b680fb4a6de5.png)

**Comment by emclaug2** [comment]
Probably related to our internal name converter function, title to snake_case?
