### ISSUE TITLE
Change repo description

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/doc-it#503]
Can I have the bounty for "noticing PX Blue in GitHub"?

![image](https://user-images.githubusercontent.com/8997218/148443196-816c31eb-1b70-45a2-9a10-6786df8b036d.png)

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/148444050-4f126030-38c4-451b-b0a8-cdceb5efaf22.png)

**Comment by LoveBlinda** [comment]
I have a big problem, please check wechat！！！

**Comment by jeffvg** [comment]
updated this
