### ISSUE TITLE
Update react-router to latest version 6.2.1

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/doc-it#519]
#### Describe the bug
Our Dependabot package updater reported the react-router should be updated from v5 to v6. Since this might be a breaking change we decided to do this manually.

#### What is the expected behavior?
Doc'it to run with latest react-router

#### Anything else to add?
https://github.com/remix-run/react-router/releases
https://reactrouter.com/docs/en/v6/upgrading/v5

Also upgrade react-router-dom from v5 to v6

**Comment by huayunh** [comment]
Is this intended to be logged under the docit repo?

**Comment by jeffvg** [comment]
> Is this intended to be logged under the docit repo?

this enhancement issue was added to all repo's that run react-router
